## File generated by the BNF Converter (bnfc 2.9.4.1).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean compiler

# Default goal.

all : Javalette/Test compiler

compiler : 
	stack build

# Rules for building the parser.

Javalette/Abs.hs Javalette/Lex.x Javalette/Par.y Javalette/Print.hs Javalette/Test.hs : src/Javalette.cf
	bnfc --haskell -d src/Javalette.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

Javalette/Test : Javalette/Abs.hs Javalette/Lex.hs Javalette/Par.hs Javalette/Print.hs Javalette/Test.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f Javalette/*.hi Javalette/*.o Javalette/*.log Javalette/*.aux Javalette/*.dvi

distclean : clean
	-rm -f Javalette/Abs.hs Javalette/Abs.hs.bak Javalette/ComposOp.hs Javalette/ComposOp.hs.bak Javalette/Doc.txt Javalette/Doc.txt.bak Javalette/ErrM.hs Javalette/ErrM.hs.bak Javalette/Layout.hs Javalette/Layout.hs.bak Javalette/Lex.x Javalette/Lex.x.bak Javalette/Par.y Javalette/Par.y.bak Javalette/Print.hs Javalette/Print.hs.bak Javalette/Skel.hs Javalette/Skel.hs.bak Javalette/Test.hs Javalette/Test.hs.bak Javalette/XML.hs Javalette/XML.hs.bak Javalette/AST.agda Javalette/AST.agda.bak Javalette/Parser.agda Javalette/Parser.agda.bak Javalette/IOLib.agda Javalette/IOLib.agda.bak Javalette/Main.agda Javalette/Main.agda.bak Javalette/Javalette.dtd Javalette/Javalette.dtd.bak Javalette/Test Javalette/Lex.hs Javalette/Par.hs Javalette/Par.info Javalette/ParData.hs Makefile
	-rmdir -p Javalette/

# EOF
